fragment PageParts on Page {
  __typename
  title
  hero {
    __typename
    badge
    heading
    subheading
    ctaPrimary
    ctaSecondary
  }
  services {
    __typename
    sectionTitle
    sectionSubtitle
  }
  contact {
    __typename
    sectionTitle
    sectionSubtitle
  }
}
