/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ElektrikerRouteImport } from './routes/elektriker'
import { Route as ExamplesRouteImport } from './routes/examples'
import { Route as IntegritetRouteImport } from './routes/integritet'
import { Route as KonsultRouteImport } from './routes/konsult'
import { Route as MalareRouteImport } from './routes/malare'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as RestaurangRouteImport } from './routes/restaurang'
import { Route as SalongRouteImport } from './routes/salong'
import { Route as VvsRouteImport } from './routes/vvs'
import { Route as ApiContactRouteImport } from './routes/api/contact'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ElektrikerRoute = ElektrikerRouteImport.update({
  id: '/elektriker',
  path: '/elektriker',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesRoute = ExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegritetRoute = IntegritetRouteImport.update({
  id: '/integritet',
  path: '/integritet',
  getParentRoute: () => rootRouteImport,
} as any)
const KonsultRoute = KonsultRouteImport.update({
  id: '/konsult',
  path: '/konsult',
  getParentRoute: () => rootRouteImport,
} as any)
const MalareRoute = MalareRouteImport.update({
  id: '/malare',
  path: '/malare',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurangRoute = RestaurangRouteImport.update({
  id: '/restaurang',
  path: '/restaurang',
  getParentRoute: () => rootRouteImport,
} as any)
const SalongRoute = SalongRouteImport.update({
  id: '/salong',
  path: '/salong',
  getParentRoute: () => rootRouteImport,
} as any)
const VvsRoute = VvsRouteImport.update({
  id: '/vvs',
  path: '/vvs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/elektriker': typeof ElektrikerRoute
  '/examples': typeof ExamplesRoute
  '/integritet': typeof IntegritetRoute
  '/konsult': typeof KonsultRoute
  '/malare': typeof MalareRoute
  '/process': typeof ProcessRoute
  '/restaurang': typeof RestaurangRoute
  '/salong': typeof SalongRoute
  '/vvs': typeof VvsRoute
  '/api/contact': typeof ApiContactRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/elektriker': typeof ElektrikerRoute
  '/examples': typeof ExamplesRoute
  '/integritet': typeof IntegritetRoute
  '/konsult': typeof KonsultRoute
  '/malare': typeof MalareRoute
  '/process': typeof ProcessRoute
  '/restaurang': typeof RestaurangRoute
  '/salong': typeof SalongRoute
  '/vvs': typeof VvsRoute
  '/api/contact': typeof ApiContactRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/elektriker': typeof ElektrikerRoute
  '/examples': typeof ExamplesRoute
  '/integritet': typeof IntegritetRoute
  '/konsult': typeof KonsultRoute
  '/malare': typeof MalareRoute
  '/process': typeof ProcessRoute
  '/restaurang': typeof RestaurangRoute
  '/salong': typeof SalongRoute
  '/vvs': typeof VvsRoute
  '/api/contact': typeof ApiContactRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/elektriker'
    | '/examples'
    | '/integritet'
    | '/konsult'
    | '/malare'
    | '/process'
    | '/restaurang'
    | '/salong'
    | '/vvs'
    | '/api/contact'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/elektriker'
    | '/examples'
    | '/integritet'
    | '/konsult'
    | '/malare'
    | '/process'
    | '/restaurang'
    | '/salong'
    | '/vvs'
    | '/api/contact'
  id:
    | '__root__'
    | '/'
    | '/elektriker'
    | '/examples'
    | '/integritet'
    | '/konsult'
    | '/malare'
    | '/process'
    | '/restaurang'
    | '/salong'
    | '/vvs'
    | '/api/contact'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ElektrikerRoute: typeof ElektrikerRoute
  ExamplesRoute: typeof ExamplesRoute
  IntegritetRoute: typeof IntegritetRoute
  KonsultRoute: typeof KonsultRoute
  MalareRoute: typeof MalareRoute
  ProcessRoute: typeof ProcessRoute
  RestaurangRoute: typeof RestaurangRoute
  SalongRoute: typeof SalongRoute
  VvsRoute: typeof VvsRoute
  ApiContactRoute: typeof ApiContactRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elektriker': {
      id: '/elektriker'
      path: '/elektriker'
      fullPath: '/elektriker'
      preLoaderRoute: typeof ElektrikerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples': {
      id: '/examples'
      path: '/examples'
      fullPath: '/examples'
      preLoaderRoute: typeof ExamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integritet': {
      id: '/integritet'
      path: '/integritet'
      fullPath: '/integritet'
      preLoaderRoute: typeof IntegritetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konsult': {
      id: '/konsult'
      path: '/konsult'
      fullPath: '/konsult'
      preLoaderRoute: typeof KonsultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/malare': {
      id: '/malare'
      path: '/malare'
      fullPath: '/malare'
      preLoaderRoute: typeof MalareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurang': {
      id: '/restaurang'
      path: '/restaurang'
      fullPath: '/restaurang'
      preLoaderRoute: typeof RestaurangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salong': {
      id: '/salong'
      path: '/salong'
      fullPath: '/salong'
      preLoaderRoute: typeof SalongRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vvs': {
      id: '/vvs'
      path: '/vvs'
      fullPath: '/vvs'
      preLoaderRoute: typeof VvsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ElektrikerRoute: ElektrikerRoute,
  ExamplesRoute: ExamplesRoute,
  IntegritetRoute: IntegritetRoute,
  KonsultRoute: KonsultRoute,
  MalareRoute: MalareRoute,
  ProcessRoute: ProcessRoute,
  RestaurangRoute: RestaurangRoute,
  SalongRoute: SalongRoute,
  VvsRoute: VvsRoute,
  ApiContactRoute: ApiContactRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
